#!/bin/bash 
#
# arcetera - arc at plusreed dot com
# Creates a commit using the 6c37 style.

color() {
				foreground="\e[0;39m"
				brown="\e[1;33m"

				printf "${brown}$@${foreground}\n"
}

while read -p "Commit: " commit; do 
				if [[ -z "$(echo "$commit" | grep -o "\.$")" && -z "$(echo $commit | grep -o ":")" ]]; then
								color "Commits should contain what you're changing and have a period at the end, try again."
				elif [[ -z "$(echo "$commit" | grep -o "\.$")" ]]; then
								color "Commits should end with a period, try again."
				elif [[ -z "$(echo "$commit" | grep -o ":")" ]]; then
								color "Commits should contain what you're changing (e.g. Add, Remove, Package name)."
				else
								break
				fi
done

git commit -m "$commit"
