#!/bin/sh

REMOTEURL="https://github.com/6c37"
PORTDIR="${PORTDIR:-$HOME/reposync}"
PORTS="\
crux-ports
crux-ports-git"

test ! -d "${PORTDIR}" && mkdir -p "${PORTDIR}"

printf '%s\n' "$PORTS" | while read -r PORT; do
    cd "${PORTDIR}"
    test ! -d "${PORTDIR}/${PORT}" && {
        git clone "${REMOTEURL}/${PORT}"
        git remote set-url origin git@github.com:6c37/${PORT}.git
    }
    cd "${PORT}"

    httpup-repgen
    git add REPO && git commit -m 'Update: REPO' && git push origin master
done
