#!/bin/sh
#
# /etc/ports/drivers/git: git driver script for ports(8)
# 

if [ $# -ne 1 ]; then
	echo "usage: $0 <file>" >&2
	exit 1
fi

. $1

if [ -z "$URL" ]; then
	echo "URL not set in '$1'" >&2
	exit 2
fi
if [ -z "$NAME" ]; then
	echo "NAME not set in '$1'" >&2
	exit 2
fi

echo "Updating collection $NAME"

if cd "$PORTS_DIR/$NAME"; then
	git fetch -q
	git whatchanged -n 1 | grep "^:" | cut -d " " -f 5- | sort | uniq | sed "s/M\t/ Edit /g; s/A\t/ Checkout /g; s/D\t/ Delete /g"
	git reset -q --hard origin/master
else
	git clone "$URL" "$PORTS_DIR/$NAME"
fi

echo "Finished successfully"
