#!/bin/sh
#
# /etc/ports/drivers/git: git driver script for ports(8)
# 

if [ $# -ne 1 ]; then
	echo "usage: $0 <file>" >&2
	exit 1
fi

. $1

if [ -z "$URL" ]; then
	echo "URL not set in '$1'" >&2
	exit 2
fi
if [ -z "$NAME" ]; then
	echo "NAME not set in '$1'" >&2
	exit 2
fi

if cd "$PORTS_DIR/$NAME"; then
	echo "Fetching ports from $URL"
	git fetch -q && git reset --hard origin/master
else
	echo "Cloning ports from $URL"
	git clone "$URL" "$PORTS_DIR/$NAME"
fi

echo "Finished successfully"
